server:
  port: 8081
spring:
  application:
    name: item-service
  datasource:
    url: jdbc:mysql://212.64.33.140:3306/hm49?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Mr.King122
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
mybatis:
  type-aliases-package: com.leyou.item.pojo